### ISSUE TITLE
[CHORE] Upgrade to `poetry` `1.4.x`

### ISSUE THREAD

**Issue by madpah** [CycloneDX/cyclonedx-python#523]
We are stuck on `poetry` `1.1.x` - let's upgrade.

**Comment by jkowalleck** [comment]
:+1: 

might include/fix #491

**Comment by madpah** [comment]
I suspect it does.

Had super weird inconsistent behaviour on numerous Python projects - so figured this was a good idea.

`poetry` release notes for `1.3.x` and `1.4.x` cite numerous improvements and preventing caches being corrupted...

**Comment by jkowalleck** [comment]
@madpah reminder: we stayed at a certain poetry version in the CI, because some range of poetry versions were broken when it came to building/bundling release packages.
The resulting packages were either not installable, IIRC.


we need to find a working version and use it.
Or maybe there is an official gh-action for this job?

**Comment by madpah** [comment]
We'll publish a RC and test it before we release `4.x.x` to ensure this is working. Good reminder @jkowalleck !

**Comment by jkowalleck** [comment]
superseded by #628

**Comment by jkowalleck** [comment]
This feature will be part of the next/upcoming major release.
Changelog: see <https://github.com/CycloneDX/cyclonedx-python/pull/605>
Install via: `pip install cyclonedx-bom==4.0.0rc1`
